name: 1.0$(rev:.r)

trigger:
  - main

resources:
  repositories:
  - repository: templates
    type: github
    name: joshjohanning/pipeline-templates
    endpoint: github.com_joshjohanning
    ref: refs/tags/v0.0.2

stages:
- stage: 'Build'
  variables:
    wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
    dotnetSdkVersion: '6.0'
    buildConfiguration: 'Release'
  jobs: 
  - template: dotnet-core-web/dotnet-core-build-simple-web-app.yml@templates
    parameters:
      buildConfiguration: '${{ variables.buildConfiguration }}'
      nugetFeed: ''
      name: 'Tailspin.SpaceGame.Web'
      projectFile: '**/Tailspin.SpaceGame.Web.csproj'
      repo: 'self'
      runSonarQube: 'false'
      sonarProjectKey: '*'
      sonarProjectName: 'Tailspin.SpaceGame.Web'
      runDotNetCoreTests: 'true'
      vmImage: 'ubuntu-latest'

- stage: deployDev
  displayName: Deploy to Dev
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables: 
    - name: azureSubscription
      value: demo-mslearn-tailspin-azure
    - group: tailspin.DEV
  jobs: 
  - template: dotnet-core-web/dotnet-core-deploy-simple-web-app.yml@templates
    parameters:
      name: 'Tailspin.SpaceGame.Web'
      environment: 
        name: 'dev'
      replaceTokensTargetFiles: |
          **/appsettings.tokenize.json => appsettings.json
          **/connectionstrings.tokenize.json => connectionstrings.json
      appSettingsEdits: '-ASPNETCORE_ENVIRONMENT Development'
      jsonVariableSubstituion: 'appsettings.json'
      azureSubscription: '${{ variables.azureSubscription }}'
      websiteName: 'app-tailspin-demo-DEV'
      resourceGroupName: 'rg-tailspin-terraform-DEV'
      deployToSlot: false

- stage: deployProd
  displayName: Deploy to Prod
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables: 
    - name: azureSubscription
      value: demo-mslearn-tailspin-azure
    - group: tailspin.PROD
  jobs: 
  - template: dotnet-core-web/dotnet-core-deploy-simple-web-app.yml@templates
    parameters:
      name: 'Tailspin.SpaceGame.Web'
      environment: 
        name: 'prod'
      replaceTokensTargetFiles: |
          **/appsettings.tokenize.json => appsettings.json
          **/connectionstrings.tokenize.json => connectionstrings.json
      appSettingsEdits: '-ASPNETCORE_ENVIRONMENT Production'
      jsonVariableSubstituion: 'appsettings.json'
      azureSubscription: '${{ variables.azureSubscription }}'
      websiteName: 'app-tailspin-demo-PROD'
      resourceGroupName: 'rg-tailspin-terraform-PROD'
      deployToSlot: false
